// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CSharpPractice.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250502005628_UpdateTable")]
    partial class UpdateTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PowerliftingResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<decimal?>("Bench4Kg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("BestBenchKg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("BestDeadliftKg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("BestSquatKg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("BodyweightKg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Deadlift4Kg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Division")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Equipment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeetID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Place")
                        .HasColumnType("int");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Squat4Kg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalKg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("WeightClassKg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Wilks")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("PowerliftingResults");
                });
#pragma warning restore 612, 618
        }
    }
}
